### ISSUE TITLE
Missing Undo / Redo

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/vscode-plugin#2]
Due to technical limitations undo and redo using Copilot is not possible. This makes it hard to undo, especially since files are not open in the editor - user doesn't even know what has been changed.

**Comment by emarc** [comment]
What will be the downside if we 1) just trigger undo in vscode, undo anything as if pressing undo in the IDE 2) show a notification in Copilot that this happened? 
Is 2) even possible to do? 

This probably warrants a planning meeting – and currently I don't even what is possible or not.

**Comment by MarcinVaadin** [comment]
In VS Code we can trigger undo for given file, same as in IntelliJ.

One drawback is that we cannot distinguish Copilot/Non-Copilot operations. Undo will just undo latest changes.

Downsides:
ad 1) we can mess up user changes using undo/redo, overwriting them with Copilot operations
ad 2) showing notification on first undo/redo with message "Undo/Redo for VS Code will affect all operations on given file, not only Copilot"

**Comment by emarc** [comment]
There seems to be two competing approaches:
a) Copilot Undo just triggers undo in the IDE, as if you would be looking at the IDE and doing Undo.
b) Copilot only does Undo for own changes = only the changes you did in Copilot while not switching back to the IDE and making a change there.

**(a)** In the IDE, you will undo both the changes made in the IDE and the changes made in Copilot. It's reasonable to assume Copilot could do the same. If you switch back and forth between coding and Copiloting, making some small adjustments here and there, I think this is the way you'd expect it to work. 

- Can we know what was undone _after_ the Undo happened in VS Code, so that we can show a notification in Copilot? This way you'd realize if you started undoing some changes you made in the IDE.
- Are there any concrete situations when it's particularly bad to just trigger undo? What is a worst case?

**(b)** On the other hand, it can be hard to see and realize what is going on in the IDE while looking at Copilot. In that sense only undoing what you _just_ did in Copilot is the "safe" choice. (Adding a notification that tells you to hop over to the IDE do continue undoing could be a helpful UX improvement.) HOWEVER this option really relies on us being able to detect if the next in the stack is a Copilot change. 

- Can we really not invent a way to identify "our" changes in the VS Code undo stack?
- Could we count the undo steps on the client side, reset on redeploy? Sounds fragile?

**Comment by MarcinVaadin** [comment]
Follow up issue https://github.com/vaadin/copilot-internal/issues/2102
